# Generated by Django 5.0.2 on 2024-05-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
