# Generated by Django 5.0.2 on 2024-05-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_post_total_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_posts',
        ),
    ]
