# Generated by Django 5.0.2 on 2024-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
