# Generated by Django 5.0.2 on 2024-05-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_photo'),
        ('User', '0007_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_Post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='Auth.post'),
            preserve_default=False,
        ),
    ]
